main: login.cgi bulletinz.cgi videoz.cgi studyz.cgi swapz.cgi reg.cgi greg.cgi bulletinzz.cgi studyzz.cgi tourist.cgi manger.cgi mg.cgi mg2.cgi manger2.cgi manger4.cgi mg4.cgi manger3.cgi mg3.cgi
login.cgi:login.cc
	g++ $^ -o $@ -lmysqlcppconn
manger.cgi:manger.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
manger3.cgi:manger3.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
mg3.cgi:mg3.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
manger4.cgi:manger4.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
mg4.cgi:mg4.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
manger2.cgi:manger2.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
mg.cgi:mg.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
mg2.cgi:mg2.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
bulletinz.cgi:bulletinz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
bulletinzz.cgi:bulletinzz.cc
	g++ $^ -o $@ -lmysqlcppconn
videoz.cgi:videoz.cc
	g++ $^ -o $@ -lmysqlcppconn
tourist.cgi:tourist.cc
	g++ $^ -o $@ -lmysqlcppconn
studyz.cgi:studyz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
studyzz.cgi:studyzz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
swapz.cgi:swapz.cc
	g++ $^ -o $@ -lmysqlcppconn
reg.cgi:reg.cc
	g++ $^ -o $@ -lmysqlcppconn
greg.cgi:greg.cc
	g++ $^ -o $@ -lmysqlcppconn



