main: login.cgi bulletinz.cgi videoz.cgi studyz.cgi swapz.cgi reg.cgi greg.cgi bulletinzz.cgi studyzz.cgi tourist.cgi
login.cgi:login.cc
	g++ $^ -o $@ -lmysqlcppconn
bulletinz.cgi:bulletinz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
bulletinzz.cgi:bulletinzz.cc
	g++ $^ -o $@ -lmysqlcppconn
videoz.cgi:videoz.cc
	g++ $^ -o $@ -lmysqlcppconn
tourist.cgi:tourist.cc
	g++ $^ -o $@ -lmysqlcppconn
studyz.cgi:studyz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
studyzz.cgi:studyzz.cc
	g++ $^ -o $@ -lmysqlcppconn -std=c++11
swapz.cgi:swapz.cc
	g++ $^ -o $@ -lmysqlcppconn
reg.cgi:reg.cc
	g++ $^ -o $@ -lmysqlcppconn
greg.cgi:greg.cc
	g++ $^ -o $@ -lmysqlcppconn



